# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

# Specify the Xcode project file
project 'iosApp.xcodeproj'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'ComposeApp', :path => '../composeApp'

end
