name: iosApp
options:
  bundleIdPrefix: com.prettyteeth
  deploymentTarget:
    iOS: "15.0"
  
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - iosApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.prettyteeth.iosApp
      FRAMEWORK_SEARCH_PATHS: 
        - $(inherited)
        - ../composeApp/build/bin/iosSimulatorArm64/debugFramework
      INFOPLIST_FILE: iosApp/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_TEAM: ""
    dependencies:
      - framework: ../composeApp/build/bin/iosSimulatorArm64/debugFramework/ComposeApp.framework
        embed: true
      - sdk: SwiftUI.framework
      - sdk: UIKit.framework
